"""Add qr_code_path to Property

Revision ID: df214b37d452
Revises: 
Create Date: 2025-07-27 10:12:55.034732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df214b37d452'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('stripe_session_id')
        batch_op.drop_column('payment_intent_id')

    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_code_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_column('qr_code_path')

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_intent_id', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('stripe_session_id', sa.VARCHAR(length=200), nullable=True))

    # ### end Alembic commands ###
